openapi: "3.0.0"

info:
  title: "Master's final project result presentation."
  description: "API to present the results of the analyses of B.pertussis strains in Catalonia."
  version: "1.0"

paths:
  /bayesian:
    post:
      description: "Known B.pertussis isolated strain variables."

      requestBody:
        description: "list [Period, Clade, ptxP, prn, fim3]"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns conditional probabilities of the missing values in html table format."
          content: 
           text/html:
              schema:
                type: string
           
    get:
      responses:
        '200':
          description: "Returns the html page to make submits."
          content:
            text/html:
              schema:
                type: string
                
  /alleles:
    get:
      responses:
          '200':
            description: "Returns the html page of the allele evolution."
            content:
              text/html:
                schema:
                  type: string
  
  /forecast:
    get:
      responses:
          '200':
            description: "Returns the html page of the Pertussis incidence forecast for Catalonia."
            content:
              text/html:
                schema:
                  type: string
                  
  /week:
    get:
      responses:
          '200':
            description: "Returns the html page of the weekly forecast."
            content:
              text/html:
                schema:
                  type: string
                  
  /annual:
    get:
      responses:
          '200':
            description: "Returns the html page of the annual forecast."
            content:
              text/html:
                schema:
                  type: string